[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | custom_components/signal_bot/__pycache__
)/
'''

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    "B",    # flake8-bugbear
    "C",    # complexity checks
    "D",    # docstring style checks
    "E",    # pycodestyle errors
    "F",    # pyflakes style checks
    "I",    # isort imports
    "ICN",  # import conventions
    "N",    # PEP8 naming
    "PGH",  # pygrep-hooks
    "PLC",  # pylint conventions
    "PLE",  # pylint errors
    "PLR",  # pylint refactoring
    "PLW",  # pylint warnings
    "PTH",  # use pathlib
    "RUF",  # ruff-specific rules
    "SIM",  # code simplification
    "T20",  # flake8-print
    "TRY",  # try/except checks
    "UP",   # pyupgrade
    "W"     # pycodestyle warnings
]
ignore = [
    "D202",    # No blank lines allowed after function docstring
    "D203",    # 1 blank line required before class docstring
    "D213",    # Multi-line docstring summary should start at the second line
    "D404",    # First word of the docstring should not be This
    "D406",    # Section name should end with a newline
    "D407",    # Section name underlining
    "D411",    # Missing blank line before section
    "E501",    # line too long (handled by black)
    "E731",    # do not assign a lambda expression, use a def
    "PLR0913", # Too many arguments
    "PLR2004"  # Magic value used in comparison
]
exclude = [
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "custom_components/signal_bot/__pycache__"
]
unfixable = ["T20", "ERA001"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"const.py" = ["N815"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["custom_components.signal_bot"]
known-third-party = ["homeassistant"]
split-on-trailing-comma = false

[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.flake8-import-conventions.aliases]
voluptuous = "vol"
