name: Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate HACS Integration
        uses: ludeeus/action-ha-validator@master

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create Release Notes
        id: release_notes
        run: |
          echo "### Release Notes" > release.md
          echo "" >> release.md
          echo "Automated release of version ${{ github.ref_name }}" >> release.md
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body_path: release.md
          draft: false
          prerelease: false
